/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum25062026;

import javax.swing.JOptionPane;

/**
 *
 * @author Andini arum karini
 */
public class gajiKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form gajiKaryawan
     */
    public gajiKaryawan() {
        initComponents();
        
        txtGajipokok.setEditable(false);
        txtUpah.setEditable(false);
        txtTotalupah.setEditable(false);
        txtTotalgaji.setEditable(false);
        txtPajak.setEditable(false);
        txtGajibersih.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        lblGaji = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNik = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        lblGol = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        cmbGol = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        txtGajipokok = new javax.swing.JTextField();
        txtUpah = new javax.swing.JTextField();
        txtTotalupah = new javax.swing.JTextField();
        lblGajipokok = new javax.swing.JLabel();
        lblUpah = new javax.swing.JLabel();
        lblTotalupah = new javax.swing.JLabel();
        lblTotalgaji = new javax.swing.JLabel();
        lblPajak = new javax.swing.JLabel();
        txtTotalgaji = new javax.swing.JTextField();
        txtPajak = new javax.swing.JTextField();
        lblGajibersih = new javax.swing.JLabel();
        txtGajibersih = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        lblGaji.setBackground(new java.awt.Color(255, 153, 255));
        lblGaji.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGaji.setText("Form Gaji Karyawan");
        lblGaji.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblNama.setText("Nama :");

        lblNik.setText("NIK :");

        lblJam.setText("Jam Kerja :");

        lblGol.setText("Golongan :");

        txtNama.setBackground(new java.awt.Color(255, 204, 255));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtNik.setBackground(new java.awt.Color(255, 204, 255));

        txtJam.setBackground(new java.awt.Color(255, 204, 255));

        cmbGol.setBackground(new java.awt.Color(255, 204, 255));
        cmbGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Gol", "1", "2", "3", "4" }));
        cmbGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGolActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(255, 153, 255));
        btnHitung.setText("Hitung Gaji");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        txtGajipokok.setBackground(new java.awt.Color(255, 204, 255));
        txtGajipokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajipokokActionPerformed(evt);
            }
        });

        txtUpah.setBackground(new java.awt.Color(255, 204, 255));
        txtUpah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpahActionPerformed(evt);
            }
        });

        txtTotalupah.setBackground(new java.awt.Color(255, 204, 255));

        lblGajipokok.setText("Gaji Pokok");

        lblUpah.setText("Upah/Jam");

        lblTotalupah.setText("Total Upah");

        lblTotalgaji.setText("Total Gaji");

        lblPajak.setText("Pajak");

        txtTotalgaji.setBackground(new java.awt.Color(255, 204, 255));

        txtPajak.setBackground(new java.awt.Color(255, 204, 255));

        lblGajibersih.setText("Gaji Bersih");

        txtGajibersih.setBackground(new java.awt.Color(255, 204, 255));
        txtGajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajibersihActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 153, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 153, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(lblGaji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addGap(52, 52, 52)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnHitung)
                                .addGap(196, 196, 196))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTotalupah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGajipokok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalgaji, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(148, 148, 148))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGol)
                                .addGap(31, 31, 31)
                                .addComponent(cmbGol, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNik)
                                    .addComponent(lblJam))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJam, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtNik)))
                            .addComponent(btnReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalgaji)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTotalupah, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUpah)
                                    .addComponent(lblGajipokok)))
                            .addComponent(lblPajak)
                            .addComponent(lblGajibersih)
                            .addComponent(btnKeluar))
                        .addGap(274, 274, 274))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblGaji)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNik)
                            .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJam)
                            .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGol)
                            .addComponent(cmbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalupah)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGajipokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGajipokok))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUpah))
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalupah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalgaji)
                    .addComponent(txtTotalgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPajak)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGajibersih)
                    .addComponent(txtGajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cmbGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGolActionPerformed

    private void txtGajipokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajipokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGajipokokActionPerformed

    private void txtUpahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpahActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        String nama = txtNama.getText();
        String nik = txtNik.getText();
        String jam = txtJam.getText();
        
        if (nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Tidak Boleh Kosong");
            txtNama.requestFocus();
            return;
            
        }
        if (nik.isEmpty()){
            JOptionPane.showMessageDialog(this, "NIK Tidak Boleh Kosong");
            txtNik.requestFocus();
            return;
        }
        if (jam.isEmpty()){
            JOptionPane.showMessageDialog(this, "NIK Tidak Boleh Kosong");
            txtJam.requestFocus();
            return;
        }
         if (cmbGol.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Golongan Belum Anda Pilih");
           
            return;
        }
        
        
        int gol = (int) cmbGol.getSelectedIndex();
            int gajiPokok = 0;
            int upahJam =0 ;
            
            switch(gol){
                case 1:
                    gajiPokok = 2000000;
                    upahJam = 20000;
                    break;
                case 2:
                    gajiPokok = 3000000;
                    upahJam = 30000;
                    break; 
                case 3:
                    gajiPokok = 3750000;
                    upahJam = 40000;
                    break;
                case 4:
                    gajiPokok = 4000000;
                    upahJam = 50000;
                    break;    
    } try{
            int jamKerja = Integer.parseInt(txtJam.getText());
            
            int totalUpah = jamKerja * upahJam;
            int totalGaji = gajiPokok + totalUpah;
            double pajak = totalGaji * 0.025;
            double gajiBersih = totalGaji - pajak;
            
            txtGajipokok.setText(String.valueOf(gajiPokok));
            txtUpah.setText(String.valueOf(upahJam));
            txtTotalupah.setText(String.valueOf(totalUpah));
            txtTotalgaji.setText(String.valueOf(totalGaji));
            txtPajak.setText(String.valueOf(pajak));
            txtGajibersih.setText(String.valueOf(gajiBersih));
            
           
                
            }catch (NumberFormatException a){
                JOptionPane.showMessageDialog(this, "Jam Kerja Yang Anda Masukkan Tidak Berupa Angka");
                txtJam.requestFocus();
            }
            
        
     
            catch (Exception a){
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan:"+a.getMessage());
            }
                 
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtGajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajibersihActionPerformed
       
    }//GEN-LAST:event_txtGajibersihActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtNik.setText("");
        txtJam.setText("");
        
        txtGajipokok.setText("");
        txtUpah.setText("");
        txtTotalupah.setText("");
        txtTotalgaji.setText("");
        txtPajak.setText("");
        txtGajibersih.setText("");
        
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
       int pil = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin  Keluar","Konfirmasi", JOptionPane.YES_NO_OPTION);
       
       if (pil == JOptionPane.YES_OPTION)
           System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbGol;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblGaji;
    private javax.swing.JLabel lblGajibersih;
    private javax.swing.JLabel lblGajipokok;
    private javax.swing.JLabel lblGol;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblPajak;
    private javax.swing.JLabel lblTotalgaji;
    private javax.swing.JLabel lblTotalupah;
    private javax.swing.JLabel lblUpah;
    private javax.swing.JTextField txtGajibersih;
    private javax.swing.JTextField txtGajipokok;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtTotalgaji;
    private javax.swing.JTextField txtTotalupah;
    private javax.swing.JTextField txtUpah;
    // End of variables declaration//GEN-END:variables
}
